Add interface for L3 routing HW offload control via ip_forward flag
xen-troops/linux pull request #132
Opened 2022-12-21 10:43 UTC by firscity

2022-12-21 12:52 UTC, LKomaryanskiy requested changes

2022-12-21 12:52 UTC, LKomaryanskiy commented on drivers/net/ethernet/renesas/rswitch.c
> +	register_netevent_notifier(&netevent_notifier);
Seems like, there has to be a unregister, instead of register.

2022-12-21 12:52 UTC, LKomaryanskiy commented on drivers/net/ethernet/renesas/rswitch.c
> +		return 0;
NIT: it can be changed to NOTIFY_DONE macro (it's equal to zero, so it's just a cosmetic change)

2022-12-21 12:52 UTC, LKomaryanskiy commented on drivers/net/ethernet/renesas/rswitch.c
> +	return 0;
The same

2022-12-21 12:52 UTC, LKomaryanskiy commented on drivers/net/ethernet/renesas/rswitch.c
> +	priv = rn->priv;
NIT: You can use "glob_priv" variable to get rswitch_private structure.

2022-12-21 13:32 UTC, LKomaryanskiy commented on drivers/net/ethernet/renesas/rswitch.c
> +	list_add(&param_list[0].list, &routing_list->param_list);
If you move list_add section before hw setup, you have to add removing them in case of any hw error too.

2022-12-21 13:32 UTC, LKomaryanskiy commented on drivers/net/ethernet/renesas/rswitch.c
> +	mutex_lock(&priv->ipv4_forward_lock);
It seems like this lock can be redundant because forward flag status has to be kept in mind only when you setup hw.

2022-12-21 13:32 UTC, LKomaryanskiy commented on drivers/net/ethernet/renesas/rswitch.c
> +	mutex_lock(&dev->priv->ipv4_forward_lock);
It seems like this lock can be redundant because forward flag status has to be kept in mind only when you setup hw.

2022-12-21 13:32 UTC, LKomaryanskiy commented on drivers/net/ethernet/renesas/rswitch.c
> +	mutex_lock(&dev->priv->ipv4_forward_lock);
It seems like this lock can be redundant because forward flag status has to be kept in mind only when you setup hw.

2022-12-21 13:32 UTC, LKomaryanskiy commented on drivers/net/ethernet/renesas/rswitch.c
> +	mutex_lock(&priv->ipv4_forward_lock);
It seems like this lock can be redundant because forward flag status has to be kept in mind only when you setup hw.

2022-12-21 15:08 UTC, Deedone commented
LGTM with Leonid's suggestions

2022-12-21 15:18 UTC, Deedone commented on drivers/net/ethernet/renesas/rswitch.c
> +					mutex_unlock(&priv->ipv4_forward_lock);
Missing lock

2022-12-21 15:27 UTC, Deedone commented on drivers/net/ethernet/renesas/rswitch.c
>  		return;
fwd_work leaks on early return

2023-01-25 12:34 UTC, LKomaryanskiy commented
Good job!
Reviewed-by: Leonid Komarianskyi <leonid_komarianskyi@epam.com>

2023-01-25 12:34 UTC, LKomaryanskiy approved these changes

2023-01-25 14:10 UTC, merged